FROM centos:7.4.1708
RUN mkdir /mydata
COPY myfiles /mydata/myfiles
ADD myfiles2 /mydata/myfile2
ADD apache-maven-3.6.3-bin.tar.gz /mydata/mavenunpack
ADD http://apachemirror.wuchna.com/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz /mydata
